#!/bin/bash

echo -e "Merge to RuzalPin \nhttps://github.com/RuzalPin/Kazan \nsite https://ruzalpin.github.io/Kazan/ "

git add --all
git commit -m "Initial commit"
git push -u origin master

echo -e "Ok...Your changes merged\n"

echo -e "Open this Kazan site?\n"

reply=''

	echo -n " y/n: "
	read reply

	if [  $reply = 'y' ] 
	then
		firefox -new-window https://ruzalpin.github.io/Kazan/

	fi
echo -e 'update web-page to look changes \n firefox - Ctrl+R'

