#!/bin/bash

echo "Merge to RuzalPin \n https://github.com/RuzalPin/Kazan \n site https://ruzalpin.github.io/Kazan/"

git add --all
git commit -m "Initial commit"
git push -u origin master

echo "Ok...Your changes merged"

echo "Open this Kazan site?"

reply=''
while ["$reply"=""]; do
	echo -n " y/n: "
	read reply

	if [ -n "$reply"="y" ]; then
		firefox https://ruzalpin.github.io/Kazan/

	fi
done

